# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelCharacterListSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelCharacterListSample
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher'

  target 'MarvelCharacterListSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelCharacterListSampleUITests' do
    # Pods for testing
  end

end
