//
//  MarvelCharactersListsView.swift
//  MarvelCharacterListSample
//
//  Created by r.a.sanz.hinojosas on 03/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol MarvelCharactersListsViewDelegate where Self: UIViewController {
    
}

final class MarvelCharactersListsView: BaseView {
    weak var delegate: MarvelCharactersListsViewDelegate?
    private var dataSource: MarvelCharactersListsModel.ViewDataSource?
    @IBOutlet weak var charactersTableView: UITableView!
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupUIComponents()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setupUIComponents()
    }
    
}

private extension MarvelCharactersListsView {
    private func setupUIComponents() {
        charactersTableView.allowsMultipleSelection = false
        self.charactersTableView.register(UINib.init(nibName: "CharactersTableViewCell", bundle: nil), forCellReuseIdentifier: "CharactersTableViewCell")
    }
}

extension MarvelCharactersListsView:  UITableViewDataSource, UITableViewDelegate {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
   
        let item = MarvelCharactersListsModel.CharactersCellModel(charecterName: "Personaje!!!!", characterImage: "http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784.jpg")
        
        guard let cell = tableView.dequeueReusableCell(withIdentifier: "CharactersTableViewCell", for: indexPath) as? CharactersTableViewCell else {
            return UITableViewCell()
        }
        
//        if let data = dataSource  {
            //            cell.prepareCell(with: data.items[indexPath.row])
        cell.prepareCell(with: item)
//        }
        return cell
    
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        print("You tapped cell number \(indexPath.row).")
        
    }

    //    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
    //
    //    }
    
}
