//
//  MarvelCharacterDetailsPresenter.swift
//  MarvelCharacterListSample
//
//  Created by r.a.sanz.hinojosas on 08/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol MarvelCharacterDetailsPresentationLogic {
  func presentResponse(_ response: MarvelCharacterDetailsModel.Response)
}

final class MarvelCharacterDetailsPresenter {
  private weak var viewController: MarvelCharacterDetailsDisplayLogic?
  
  init(viewController: MarvelCharacterDetailsDisplayLogic?) {
    self.viewController = viewController
  }
}


// MARK: - MarvelCharacterDetailsPresentationLogic
extension MarvelCharacterDetailsPresenter: MarvelCharacterDetailsPresentationLogic {
  
  func presentResponse(_ response: MarvelCharacterDetailsModel.Response) {
    
    switch response {
      
    case .doSomething(let theNewItem, let isItem):
      presentDoSomething(theNewItem, isItem)
    }
  }
}


// MARK: - Private Zone
private extension MarvelCharacterDetailsPresenter {
  
  func presentDoSomething(_ newItem: Int, _ isItem: Bool) {
    
    //prepare data for display and send it further
    
    viewController?.displayViewModel(.doSomething(viewModelData: NSObject()))
  }
}
