//
//  MarvelCharacterDetailsView.swift
//  MarvelCharacterListSample
//
//  Created by r.a.sanz.hinojosas on 08/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol MarvelCharacterDetailsViewDelegate where Self: UIViewController {
    
    func sendDataBackToParent(_ data: Data)
}

final class MarvelCharacterDetailsView: BaseView {
    
    weak var delegate: MarvelCharacterDetailsViewDelegate?
    
    @IBOutlet weak var containerView: UIView!
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var characterImage: UIImageView!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var lastAppearanceLabel: UILabel!
    
    private var dataSource: MarvelCharacterDetailsModel.ViewDataSource?
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupUIComponents()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setupUIComponents()
    }
    
    func updateDataSource(with dataSource: MarvelCharacterDetailsModel.ViewDataSource) {
      self.dataSource = dataSource
        titleLabel.text = dataSource.characterName
        descriptionLabel.text = dataSource.characterDescription
        lastAppearanceLabel.text = dataSource.characterLastAppearance
        
        if let path = dataSource.imageName {
          let urlImage = URL(string: path)
            characterImage.kf.setImage(with: urlImage)
        }
    }
}

private extension MarvelCharacterDetailsView {
    private func setupUIComponents() {
        containerView.layer.cornerRadius = 20
        
    }
}

