//
//  MarvelCharacterDetailsFactorable.swift
//  MarvelCharacterListSample
//
//  Created by r.a.sanz.hinojosas on 08/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

extension AppInjector {
  
  struct MarvelCharacterDetailsInjector {}
}

extension AppInjector.MarvelCharacterDetailsInjector: MarvelCharacterDetailsFactorable {}

protocol MarvelCharacterDetailsFactorable: MarvelCharacterDetailsInteractorFactorable, MarvelCharacterDetailsPresenterFactorable, MarvelCharacterDetailsRouterFactorable, MarvelCharacterDetailsServicesFactorable { }

protocol MarvelCharacterDetailsInteractorFactorable {
  typealias InteractableFactory = MarvelCharacterDetailsPresenterFactorable & MarvelCharacterDetailsServicesFactorable
  
  func makeInteractor(factory: InteractableFactory, viewController: MarvelCharacterDetailsDisplayLogic?, dataSource: MarvelCharacterDetailsModel.DataSource) -> MarvelCharacterDetailsInteractable
}

protocol MarvelCharacterDetailsPresenterFactorable {
  func makePresenter(viewController: MarvelCharacterDetailsDisplayLogic?) -> MarvelCharacterDetailsPresentationLogic
}

protocol MarvelCharacterDetailsRouterFactorable {
  func makeRouter(viewController: UIViewController?) -> MarvelCharacterDetailsRouting
}

extension MarvelCharacterDetailsFactorable {
  
  func makeInteractor(factory: InteractableFactory, viewController: MarvelCharacterDetailsDisplayLogic?, dataSource: MarvelCharacterDetailsModel.DataSource) -> MarvelCharacterDetailsInteractable {
    MarvelCharacterDetailsInteractor(factory: factory, viewController: viewController, dataSource: dataSource)
  }
  
  func makePresenter(viewController: MarvelCharacterDetailsDisplayLogic?) -> MarvelCharacterDetailsPresentationLogic {
    MarvelCharacterDetailsPresenter(viewController: viewController)
  }
  
  func makeRouter(viewController: UIViewController?) -> MarvelCharacterDetailsRouting {
    MarvelCharacterDetailsRouter(viewController: viewController)
  }
}


// MARK: - Service Factorable
protocol MarvelCharacterDetailsServicesFactorable {
  
  //func makeXService() -> xService
}

extension MarvelCharacterDetailsServicesFactorable {
  
  //func makeXService() -> xService {
  //   xService()
  //}
}
