//
//  MarvelCharacterDetailsViewController.swift
//  MarvelCharacterListSample
//
//  Created by r.a.sanz.hinojosas on 08/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol MarvelCharacterDetailsDisplayLogic where Self: UIViewController {
  
  func displayViewModel(_ viewModel: MarvelCharacterDetailsModel.ViewModel)
}

final class MarvelCharacterDetailsViewController: UIViewController {
  
  typealias MarvelCharacterDetailsFactory = MarvelCharacterDetailsInteractorFactorable & MarvelCharacterDetailsRouterFactorable

  private let mainView: MarvelCharacterDetailsView
  private var interactor: MarvelCharacterDetailsInteractable!
  private var router: MarvelCharacterDetailsRouting!
  
  required init(factory: MarvelCharacterDetailsFactory, mainView: MarvelCharacterDetailsView, dataSource: MarvelCharacterDetailsModel.DataSource) {
    self.mainView = mainView
    
    super.init(nibName: nil, bundle: nil)
    
    let interactorFactory = factory as! MarvelCharacterDetailsInteractorFactorable.InteractableFactory
    interactor = factory.makeInteractor(factory: interactorFactory, viewController: self, dataSource: dataSource)
    router = factory.makeRouter(viewController: self)
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    //interactor.doSomething(item: 22)
  }
  
  override func loadView() {
    mainView.delegate = self
    view = mainView
  }

  @available(*, unavailable)
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented, You shouldn't initialize the ViewController using Storyboards")
  }
}

// MARK: - MarvelCharacterDetailsDisplayLogic
extension MarvelCharacterDetailsViewController: MarvelCharacterDetailsDisplayLogic {

  func displayViewModel(_ viewModel: MarvelCharacterDetailsModel.ViewModel) {
    DispatchQueue.main.async {
      switch viewModel {

      case .doSomething(let viewModel):
        self.displayDoSomething(viewModel)
      }
    }
  }
}


// MARK: - MarvelCharacterDetailsViewDelegate
extension MarvelCharacterDetailsViewController: MarvelCharacterDetailsViewDelegate {
  
  func sendDataBackToParent(_ data: Data) {
    //usually this delegate takes care of user actions and requests through UI
    
    //do something with the data or message sent back from mainView
  }
}


// MARK: - Private Zone
private extension MarvelCharacterDetailsViewController {
  
  func displayDoSomething(_ viewModel: NSObject) {
    print("Use the mainView to present the viewModel")
    //example of using router
    router.routeTo(.xScene(xData: 22))
  }
}
