//
//  MarvelCharacterDetailsInteractor.swift
//  MarvelCharacterListSample
//
//  Created by r.a.sanz.hinojosas on 08/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

typealias MarvelCharacterDetailsInteractable = MarvelCharacterDetailsBusinessLogic & MarvelCharacterDetailsDataStore

protocol MarvelCharacterDetailsBusinessLogic {
  
  func doRequest(_ request: MarvelCharacterDetailsModel.Request)
}

protocol MarvelCharacterDetailsDataStore {
  var dataSource: MarvelCharacterDetailsModel.DataSource { get }
}

final class MarvelCharacterDetailsInteractor: MarvelCharacterDetailsDataStore {
  
  var dataSource: MarvelCharacterDetailsModel.DataSource
  
  private var factory: MarvelCharacterDetailsInteractorFactorable.InteractableFactory
  private var presenter: MarvelCharacterDetailsPresentationLogic
  
  init(factory: MarvelCharacterDetailsInteractorFactorable.InteractableFactory, viewController: MarvelCharacterDetailsDisplayLogic?, dataSource: MarvelCharacterDetailsModel.DataSource) {
    self.factory = factory
    self.dataSource = dataSource
    self.presenter = factory.makePresenter(viewController: viewController)
  }
}


// MARK: - MarvelCharacterDetailsBusinessLogic
extension MarvelCharacterDetailsInteractor: MarvelCharacterDetailsBusinessLogic {
  
  func doRequest(_ request: MarvelCharacterDetailsModel.Request) {
    DispatchQueue.global(qos: .userInitiated).async {
      
      switch request {
        
      case .doSomething(let item):
        self.doSomething(item)
      }
    }
  }
}


// MARK: - Private Zone
private extension MarvelCharacterDetailsInteractor {
  
  func doSomething(_ item: Int) {
    
    //construct the Service right before using it
    //let serviceX = factory.makeXService()
    
    // get new data async or sync
    //let newData = serviceX.getNewData()
    
    presenter.presentResponse(.doSomething(newItem: item + 1, isItem: true))
  }
}
