//
//  MarvelCharactersListsViewController.swift
//  MarvelCharacterListSample
//
//  Created by r.a.sanz.hinojosas on 03/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol MarvelCharactersListsDisplayLogic where Self: UIViewController {
    func displayViewModel(_ viewModel: MarvelCharactersListsModel.ViewModel)
    
}

final class MarvelCharactersListsViewController: BaseViewController {
    
    typealias MarvelCharactersListsFactory = MarvelCharactersListsInteractorFactorable & MarvelCharactersListsRouterFactorable
    
    private let mainView: MarvelCharactersListsView
    private var interactor: MarvelCharactersListsInteractable!
    private var router: MarvelCharactersListsRouting!
    
    required init(factory: MarvelCharactersListsFactory, mainView: MarvelCharactersListsView, dataSource: MarvelCharactersListsModel.DataSource) {
        self.mainView = mainView
        
        super.init(nibName: nil, bundle: nil)
        
        let interactorFactory = factory as! MarvelCharactersListsInteractorFactorable.InteractableFactory
        interactor = factory.makeInteractor(factory: interactorFactory, viewController: self, dataSource: dataSource)
        router = factory.makeRouter(viewController: self)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor.doRequest(.extractCharactersList(page:0))
        
    }
    
    override func loadView() {
        mainView.delegate = self
        view = mainView
        
    }
    
    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented, You shouldn't initialize the ViewController using Storyboards")
    }
}

// MARK: - MarvelCharactersListsDisplayLogic
extension MarvelCharactersListsViewController: MarvelCharactersListsDisplayLogic {
    
    func displayViewModel(_ viewModel: MarvelCharactersListsModel.ViewModel) {
        DispatchQueue.main.async {
            switch viewModel {
            case .showCharactersListInVC(let viewModelData):
                self.navigationItem.title = viewModelData.title
                self.mainView.updateDataSource(with: viewModelData)
            case .showCharacterDetailsInVC(let id):
                self.router.routeTo(.sendIdToDetailsScreen(id: id))
            }
        }
    }
}


// MARK: - MarvelCharactersListsViewDelegate
extension MarvelCharactersListsViewController: MarvelCharactersListsViewDelegate {
    func characterSelected(selected: Int) {
        interactor.doRequest(.characterSelected(selected: selected))
    }
    
    func nextPage(page: Int) {
        interactor.doRequest(.extractCharactersList(page: page))
    }

}


// MARK: - Private Zone
private extension MarvelCharactersListsViewController {
    func displayDoSomething(_ viewModel: NSObject) {
        print("Use the mainView to present the viewModel")
    }
}
