//
//  MarvelCharactersListsFactorable.swift
//  MarvelCharacterListSample
//
//  Created by r.a.sanz.hinojosas on 03/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit



extension AppInjector {
  
  struct MarvelCharactersListsInjector {}
}

extension AppInjector.MarvelCharactersListsInjector: MarvelCharactersListsFactorable {}

protocol MarvelCharactersListsFactorable: MarvelCharactersListsInteractorFactorable, MarvelCharactersListsPresenterFactorable, MarvelCharactersListsRouterFactorable, MarvelCharactersListsServicesFactorable { }

protocol MarvelCharactersListsInteractorFactorable {
  typealias InteractableFactory = MarvelCharactersListsPresenterFactorable & MarvelCharactersListsServicesFactorable
  
  func makeInteractor(factory: InteractableFactory, viewController: MarvelCharactersListsDisplayLogic?, dataSource: MarvelCharactersListsModel.DataSource) -> MarvelCharactersListsInteractable
}

protocol MarvelCharactersListsPresenterFactorable {
  func makePresenter(viewController: MarvelCharactersListsDisplayLogic?) -> MarvelCharactersListsPresentationLogic
}

protocol MarvelCharactersListsRouterFactorable {
  func makeRouter(viewController: UIViewController?) -> MarvelCharactersListsRouting
}

extension MarvelCharactersListsFactorable {
  
  func makeInteractor(factory: InteractableFactory, viewController: MarvelCharactersListsDisplayLogic?, dataSource: MarvelCharactersListsModel.DataSource) -> MarvelCharactersListsInteractable {
    MarvelCharactersListsInteractor(factory: factory, viewController: viewController, dataSource: dataSource)
  }
  
  func makePresenter(viewController: MarvelCharactersListsDisplayLogic?) -> MarvelCharactersListsPresentationLogic {
    MarvelCharactersListsPresenter(viewController: viewController)
  }
  
  func makeRouter(viewController: UIViewController?) -> MarvelCharactersListsRouting {
    MarvelCharactersListsRouter(viewController: viewController)
  }
}


// MARK: - Service Factorable
protocol MarvelCharactersListsServicesFactorable {
  
  //func makeXService() -> xService
}

extension MarvelCharactersListsServicesFactorable {
  
  //func makeXService() -> xService {
  //   xService()
  //}
}
