//
//  MarvelCharactersListsPresenter.swift
//  MarvelCharacterListSample
//
//  Created by r.a.sanz.hinojosas on 03/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol MarvelCharactersListsPresentationLogic {
  func presentResponse(_ response: MarvelCharactersListsModel.Response)
}

final class MarvelCharactersListsPresenter {
  private weak var viewController: MarvelCharactersListsDisplayLogic?
  
  init(viewController: MarvelCharactersListsDisplayLogic?) {
    self.viewController = viewController
  }
}


// MARK: - MarvelCharactersListsPresentationLogic
extension MarvelCharactersListsPresenter: MarvelCharactersListsPresentationLogic {
  
  func presentResponse(_ response: MarvelCharactersListsModel.Response) {
    
    switch response {
      
    case .doSomething(let theNewItem, let isItem):
      presentDoSomething(theNewItem, isItem)
    }
  }
}


// MARK: - Private Zone
private extension MarvelCharactersListsPresenter {
  
  func presentDoSomething(_ newItem: Int, _ isItem: Bool) {
    
    //prepare data for display and send it further
    
    viewController?.displayViewModel(.doSomething(viewModelData: NSObject()))
  }
}
